#!/usr/bin/env bash
set -euo pipefail

# admin/apply-db-users.sh
# ----------------------
# Applies DB users from admin/db-users.txt to MariaDB.
#
# File format: CSV with 3 fields:
#   account,password,priv
#
# Requirements:
# - The schema/header line MUST be commented, e.g.:
#     # account,password,priv
# - Lines starting with # are comments and ignored
# - Blank lines ignored
#
# priv values:
#   r = read-only       (SELECT)
#   w = read/write      (SELECT, INSERT, UPDATE, DELETE)
#   a = admin on schema (ALL PRIVILEGES on DB)
#
# Safe to re-run:
# - CREATE USER IF NOT EXISTS
# - ALTER USER to sync password
# - GRANT appropriate privileges
#
# Options:
#   --dry-run   Print what would be done (including SQL), but do not execute.
#   --file PATH Use alternate db-users file (default: admin/db-users.txt)
#   --db NAME   Target DB name (default: uls)
#   --container NAME  DB container name (default: arcs-uls-mariadb)

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

DB_USERS_FILE="${PROJECT_ROOT}/admin/db-users.txt"
DB_CONTAINER="${DB_CONTAINER:-arcs-uls-mariadb}"
DB_NAME="${DB_NAME:-uls}"
DRY_RUN=0

usage() {
  cat <<USAGE
Usage: $0 [--dry-run] [--file PATH] [--db NAME] [--container NAME]

Applies DB users from a CSV file with lines:
  username,password,priv

Header/schema line must be commented:
  # account,password,priv
USAGE
}

log() { echo "[apply-db-users] $*"; }
die() { echo "[apply-db-users][ERROR] $*" >&2; exit 1; }
warn() { echo "[apply-db-users][WARN] $*" >&2; }

# ------------------------------------------------------------
# Args
# ------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    --file) DB_USERS_FILE="$2"; shift 2 ;;
    --db) DB_NAME="$2"; shift 2 ;;
    --container) DB_CONTAINER="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown argument: $1 (use --help)" ;;
  esac
done

[[ -f "$DB_USERS_FILE" ]] || die "Missing file: $DB_USERS_FILE"

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------
trim() { echo -n "$1" | xargs; }

is_valid_user() {
  # MySQL/MariaDB usernames are generally up to 80 chars; keep conservative.
  # Allow letters, digits, underscore, dash, dot.
  [[ "$1" =~ ^[A-Za-z0-9._-]{1,64}$ ]]
}

# ------------------------------------------------------------
# Validate file header rule
# ------------------------------------------------------------
if grep -nE '^[[:space:]]*account[[:space:]]*,[[:space:]]*password[[:space:]]*,[[:space:]]*priv[[:space:]]*$' "$DB_USERS_FILE" >/dev/null 2>&1; then
  die "Found an uncommented header line 'account,password,priv'. It must be commented: '# account,password,priv'"
fi

# ------------------------------------------------------------
# Parse + validate + build SQL
# ------------------------------------------------------------
tmp_sql=""
tmp_sql="$(mktemp)"
trap '[[ -n "${tmp_sql:-}" ]] && rm -f "$tmp_sql"' EXIT

declare -A seen_users=()
declare -a plan=()

{
  echo "-- Generated by admin/apply-db-users.sh"
  echo "USE \`$DB_NAME\`;"
} > "$tmp_sql"

line_no=0
while IFS= read -r raw || [[ -n "$raw" ]]; do
  line_no=$((line_no + 1))
  line="$(trim "$raw")"

  [[ -z "$line" ]] && continue
  [[ "$line" =~ ^# ]] && continue

  # Must be exactly 3 CSV fields (no commas in password supported in this v1 parser)
  IFS=',' read -r account password priv extra <<<"$line"

  if [[ -n "${extra:-}" ]]; then
    die "Line $line_no: too many fields. Expected exactly 3: account,password,priv"
  fi

  account="$(trim "${account:-}")"
  password="$(trim "${password:-}")"
  priv="$(trim "${priv:-}")"

  [[ -n "$account" && -n "$password" && -n "$priv" ]] || die "Line $line_no: missing field(s). Expected: account,password,priv"

  if ! is_valid_user "$account"; then
    die "Line $line_no: invalid account '$account'. Allowed: A-Z a-z 0-9 . _ - (1..64 chars)"
  fi

  case "$priv" in
    r|w|a) ;;
    *) die "Line $line_no: invalid priv '$priv' (use r, w, or a)" ;;
  esac

  if [[ -n "${seen_users[$account]:-}" ]]; then
    die "Line $line_no: duplicate account '$account' (already defined on line ${seen_users[$account]})"
  fi
  seen_users["$account"]="$line_no"

  # Escape single quotes in SQL literals
  pw_escaped="${password//\'/\'\'}"

  case "$priv" in
    r) grant_sql="GRANT SELECT ON \`$DB_NAME\`.* TO '${account}'@'%';" ;;
    w) grant_sql="GRANT SELECT, INSERT, UPDATE, DELETE ON \`$DB_NAME\`.* TO '${account}'@'%';" ;;
    a) grant_sql="GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '${account}'@'%';" ;;
  esac

  cat >> "$tmp_sql" <<SQL
CREATE USER IF NOT EXISTS '${account}'@'%' IDENTIFIED BY '${pw_escaped}';
ALTER USER '${account}'@'%' IDENTIFIED BY '${pw_escaped}';
${grant_sql}
SQL

  plan+=("${account}:${priv}")
done < "$DB_USERS_FILE"

echo "FLUSH PRIVILEGES;" >> "$tmp_sql"

if [[ ${#plan[@]} -eq 0 ]]; then
  warn "No accounts found to apply (file has no uncommented account lines)."
  exit 0
fi

# ------------------------------------------------------------
# Dry-run output
# ------------------------------------------------------------
log "Target DB: ${DB_NAME}"
log "DB container: ${DB_CONTAINER}"
log "Accounts to apply (${#plan[@]}):"
for p in "${plan[@]}"; do
  log "  - ${p}"
done

if (( DRY_RUN == 1 )); then
  echo
  log "--dry-run enabled. Not executing SQL."
  echo
  log "Generated SQL:"
  echo "------------------------------------------------------------"
  cat "$tmp_sql"
  echo "------------------------------------------------------------"
  exit 0
fi

# ------------------------------------------------------------
# Execute SQL
# ------------------------------------------------------------
log "Executing SQL in container..."
docker exec -i "$DB_CONTAINER" sh -lc '
set -eu
DBPASS="$(cat /run/secrets/mariadb_root_password)"
mariadb -uroot -p"$DBPASS"
' < "$tmp_sql"

log "Done."
